-- Update the status enum to include all required values
ALTER TABLE expenses MODIFY COLUMN status ENUM('SUBMITTED','HR_APPROVED','POLICY_EXCEPTION','MANAGER_APPROVED','MANAGER_APPROVED_FOR_VERIFICATION','MANAGER_REJECTED','PENDING_FINANCE_REVIEW','FINANCE_APPROVED','FINANCE_REJECTED','PAID') DEFAULT 'SUBMITTED';

-- Verify the change
DESCRIBE expenses;
